@extends('layouts.admin')
@section('title','Bulk Article Number')
@section('content')
<div class="container-fluid py-3"><div class="d-flex justify-content-between align-items-center mb-3"><h3>Bulk Article Number</h3><a href="{{ route('admin.bulk-article.history') }}" class="btn btn-outline-secondary">Article / Tracking History</a></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="card mb-3"><div class="card-header fw-bold">Filter paid orders</div><div class="card-body"><form class="row g-2 align-items-end" method="get"><div class="col-md-2"><label class="form-label">Start Date</label><input class="form-control" type="date" name="start_date" value="{{ $start }}"></div><div class="col-md-2"><label class="form-label">End Date</label><input class="form-control" type="date" name="end_date" value="{{ $end }}"></div><div class="col-md-2"><label class="form-label">Tracking Status</label><select class="form-select" name="tracking_status"><option value="not_yet" @selected(request('tracking_status','not_yet')==='not_yet')>Not Yet</option><option value="generated" @selected(request('tracking_status')==='generated')>Generated</option><option value="all" @selected(request('tracking_status')==='all')>All</option></select></div><div class="col-md-3"><label class="form-label">Client Name</label><input class="form-control" name="client_name" value="{{ request('client_name') }}"></div><div class="col-md-2"><button class="btn btn-primary">Apply Filter</button></div></form></div></div>
<form method="post" action="{{ route('admin.bulk-article.proceed') }}">@csrf<div class="card mb-3"><div class="card-header d-flex justify-content-between"><strong>Successful + Paid Orders</strong><button class="btn btn-sm btn-primary">Proceed with Selected</button></div><div class="table-responsive"><table class="table table-striped mb-0"><thead><tr><th><input type="checkbox" id="selectAll"></th><th>Order ID</th><th>Date</th><th>Client</th><th>Phone</th><th>Address</th><th>Amount</th><th>Payment</th><th>Tracking Status</th></tr></thead><tbody>@forelse($orders as $order)<tr><td><input type="checkbox" name="order_ids[]" value="{{ $order->id }}"></td><td>{{ $order->order_number }}</td><td>{{ optional($order->sale_date ?? $order->created_at)->format('d-m-Y') }}</td><td>{{ $order->customer_name }}</td><td>{{ $order->customer_phone }}</td><td>{{ $order->full_address }}</td><td>₹{{ number_format($order->grand_total,2) }}</td><td>{{ ucfirst($order->payment_status) }}</td><td>@if($order->shipment || $order->tracking_number)<span class="badge bg-success">Generated</span>@else<span class="badge bg-secondary">Not Yet</span>@endif</td></tr>@empty<tr><td colspan="9" class="text-center p-4">No eligible orders for these filters.</td></tr>@endforelse</tbody></table></div><div class="card-body">{{ $orders->links() }}</div></div></form>
<div class="card"><div class="card-header d-flex justify-content-between align-items-center"><strong>Selected Orders / Processing Bucket</strong><span>Total Selected Orders: {{ $bucket->count() }}</span></div><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Remove</th><th>Order ID</th><th>Client</th><th>Address</th><th>Amount</th><th>Date</th></tr></thead><tbody>@forelse($bucket as $order)<tr><td><form method="post" action="{{ route('admin.bulk-article.remove',$order->id) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Remove</button></form></td><td>{{ $order->order_number }}</td><td>{{ $order->customer_name }}</td><td>{{ $order->full_address }}</td><td>₹{{ number_format($order->grand_total,2) }}</td><td>{{ $order->created_at?->format('d-m-Y') }}</td></tr>@empty<tr><td colspan="6" class="text-center p-3">No orders selected.</td></tr>@endforelse</tbody></table></div>@if($bucket->isNotEmpty())<div class="card-footer text-end"><button class="btn btn-success" type="button" data-bs-toggle="modal" data-bs-target="#confirmApply">Apply</button></div>@endif</div>
<div class="modal fade" id="confirmApply" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><div class="modal-header"><h5>Confirm Courier Article Upload</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body">You have selected {{ $bucket->count() }} orders for courier article number generation. Continue?</div><div class="modal-footer"><button class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button><a class="btn btn-primary" href="{{ route('admin.bulk-article.upload') }}">Continue</a></div></div></div></div></div>
<script>document.getElementById('selectAll')?.addEventListener('change',e=>document.querySelectorAll('input[name="order_ids[]"]').forEach(x=>x.checked=e.target.checked));</script>
@endsection
